### ISSUE TITLE
Web Integrator?

### ISSUE THREAD

**Issue by JGrotex** [retgits/tci-flogo-ifttt-extension#2]
Can you replace "Web Integrator" with "Flogo" within the '**readme.md**' please?
many thanks, Jörg

**Comment by retgits** [comment]
Can you let me know why you want me to change that?

**Comment by JGrotex** [comment]
Hi Leon,

as there is no "Web Integrator" anymore? ... Just Flogo.
BTW: this Sample is still used by some Documentation Sites, so it could
confuse People, or what do think?

many thanks & regards, Jörg

*Jörg Grote **- *Office of the CTO - Principal Solutions Architect | *M*  +49
171 5664 015 | *E* jgrote@tibco.com | *W* www.tibco.com | *TIBCO Software*
|  3307 Hillview Avenue, Palo Alto, CA 94304
<https://maps.google.com/?q=3307+Hillview+Avenue,+Palo+Alto,+CA+94304&entry=gmail&source=g>

<https://github.com/jgrotex>      <https://www.linkedin.com/in/jgrote/>
<https://twitter.com/JoergGODev>

*TIBCO Cloud Live Apps - **Build smart apps in minutes.* *more **Details
here ... <https://www.tibco.com/products/tibco-cloud-live-apps>*

<https://now.tibco.com/>

The information transmitted in this electronic communication is intended
only for the person or entity to whom it is addressed and may contain
confidential and/or privileged material. Any review, retransmission,
dissemination or other use of or taking of any action in reliance upon this
information by persons or entities other than the intended recipient is
prohibited.





Am Mo., 17. Juni 2019 um 15:45 Uhr schrieb Leon Stigter <
notifications@github.com>:

**Comment by JGrotex** [comment]
so the 'old' wrong name persist?

**Comment by retgits** [comment]
no it doesn't...

**Comment by JGrotex** [comment]
what about this?
"An extension for TIBCO Cloud Integration - **Web Integrator** to connect ..."
