### ISSUE TITLE
ivValues not being passed into webhook

### ISSUE THREAD

**Issue by iainharfield** [retgits/tci-flogo-ifttt-extension#3]
Hi, I'm trying to use this activity and noticed that values were being passed into the webhook call. I'm passing in 3 parameters (max allowed) but looking at the logic if ivValue3 has a value nothing is passed in:

if context.GetInput(ivValue3) == nil {
    data = Payload{Value1: context.GetInput(ivValue1).(string), Value2: context.GetInput(ivValue2).(string)}
} else if context.GetInput(ivValue2) == nil {
     data = Payload{Value1: context.GetInput(ivValue1).(string)}
}

I've temporarily fixed with....
data = Payload{Value1: context.GetInput(ivValue1).(string), Value2: context.GetInput(ivValue2).(string),  Value3: context.GetInput(ivValue3).(string)}

thanks
Iain

**Comment by retgits** [comment]
Hi Iain,

You're right, good catch! A newer version of the code is in my Flogo-Components repository (https://github.com/retgits/flogo-components/blob/master/activity/iftttwebhook), but I'll update the code here too.
